# Generated by Django 4.0.2 on 2022-08-28 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writehelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('createdtimes', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('prices', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('semestr', models.IntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('subjects', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предмет')),
                ('institutes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Институт')),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helped_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Просьба о помощи',
                'verbose_name_plural': 'Просьбы о помощи',
            },
        ),
        migrations.CreateModel(
            name='WhiteHelpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/writehelp/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.writehelp')),
            ],
            options={
                'verbose_name': 'Файлы для помощника',
                'verbose_name_plural': 'Файлы для помощников',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('createdtime', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('number_course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('number_semestr', models.IntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('subjectt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предмет')),
                ('type_materials', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип работы')),
                ('institute', models.CharField(blank=True, max_length=200, null=True, verbose_name='Институт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Загрузка файла',
                'verbose_name_plural': 'Загрузка файлов',
            },
        ),
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.uploadfile')),
            ],
            options={
                'verbose_name': 'Файлы документа',
                'verbose_name_plural': 'Файлы документов',
            },
        ),
        migrations.CreateModel(
            name='chatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('correspondents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondents', to=settings.AUTH_USER_MODEL)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
